Adds save_cache builder

diff --git a/save_cache/cloudbuild.yaml b/save_cache/cloudbuild.yaml
--- a/save_cache/cloudbuild.yaml
+++ b/save_cache/cloudbuild.yaml
@@ -12,36 +12,36 @@ steps:
   args: 
   - '-c'
   - |
-    mkdir -p /cache/folder1 /cache/folder2/subfolder3
-    touch /cache/folder1/file1.txt
-    touch /cache/folder1/file2.txt
-    touch /cache/folder2/ignore.txt
-    touch /cache/folder2/subfolder3/file1.txt
-  volumes:
-  - name: 'cache'
-    path: '/cache'
+    echo "Creating test cache file structure."
+    mkdir -p cache/folder1 cache/folder2/subfolder3
+    touch cache/folder1/file1.txt
+    touch cache/folder1/file2.txt
+    touch cache/folder2/ignore.txt
+    touch cache/folder2/subfolder3/file1.txt
 
 - name: 'gcr.io/$PROJECT_ID/save_cache'
   args:
-  - '--out=/cache'
+  - '--out=cache'
   - '--key=simple-key-$( checksum cloudbuild.yaml )'
-  - '--path=/cache/folder1'
-  - '--path=/cache/folder2/subfolder3'
-  volumes:
-  - name: 'cache'
-    path: '/cache'
+  - '--path=cache/folder1'
+  - '--path=cache/folder2/subfolder3'
 
 - name: 'gcr.io/$PROJECT_ID/save_cache'
   entrypoint: '/bin/bash'
   args:
   - '-c'
   - |
-    ls -al /cache
-    test -f /cache/simple-key-$( checksum cloudbuild.yaml ).tgz || echo "`ls -al /cache`"
-  volumes:
-  - name: 'cache'
-    path: '/cache'
+    echo "Verifying cache file exists."
 
+    cache_file="cache/simple-key-$( checksum cloudbuild.yaml ).tgz"
+    if [[ ! -f "${cache_file}" ]];then
+      echo "Missing cache file at ${cache_file}"
+      echo "Contents:"
+      echo "$(ls -al cache)"
+      exit 1
+    fi
+
+    echo "Tests passed."
 
 substitutions:
   _VERSION: '1.0'
